name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown
        
    - name: Download trunk
      run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
      
    - name: Build
      run: ./trunk build
      
    - name: Make wasm paths relative
      run: cat ./dist/index.html | sed "s@'/@'./@g" | sed 's@"/@"./@g' > ./dist/index.html
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: IdMangler
        path: dist/
        
  clippy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Add clippy
        run: rustup component add clippy
      
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
